image:
  file: .gitpod/Dockerfile
  context: .gitpod
ports:
- port: 8080
  onOpen: open-browser
- port: 9000
  onOpen: ignore
- port: 3306
  onOpen: ignore
tasks:
- name: Logs
  init: |
    composer install
    yarn install
    cp .gitpod/config.inc.php .
  command: |
    supervisord --nodaemon
